org: danielmurilo
service: teste-backend-ticket

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: sa-east-1

functions:
  listAllRequests:
    handler: src/functions/requests/list.handler
    events:
      - httpApi:
          path: /requests
          method: get
  listOneRequest:
    handler: src/functions/requests/list-one.handler
    events:
      - httpApi:
          path: /requests/{id}
          method: get
  createRequest:
    handler: src/functions/requests/create.handler
    events:
      - httpApi:
          path: /requests
          method: post
