org: danielmurilo
service: teste-backend-ticket

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: sa-east-1
  stage: ${opt:stage, 'dev'}

  logs:
    httpApi: true

  logRetentionInDays: 7

  environment:
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}
    DATABASE_URL:
      Fn::Join:
        - ""
        - - "postgresql://"
          - ${self:custom.dbUser}
          - ":"
          - ${self:custom.dbPassword}
          - "@"
          - Fn::GetAtt: [RdsInstance, Endpoint.Address]
          - ":5432/"
          - ${self:custom.dbName}

custom:
  dbName: testebackenddb
  dbUser: postgres
  dbPassword: ${ssm:/teste-backend-ticket/db/password}

functions:
  listAllRequests:
    handler: src/functions/requests/list.handler
    logs:
      logGroup: /aws/lambda/${self:service}-${self:provider.stage}-listAllRequests
    events:
      - httpApi:
          path: /requests
          method: get

  listOneRequest:
    handler: src/functions/requests/list-one.handler
    logs:
      logGroup: /aws/lambda/${self:service}-${self:provider.stage}-listOneRequest
    events:
      - httpApi:
          path: /requests/{id}
          method: get

  createRequest:
    handler: src/functions/requests/create.handler
    logs:
      logGroup: /aws/lambda/${self:service}-${self:provider.stage}-createRequest
    events:
      - httpApi:
          path: /requests
          method: post

resources:
  Resources:
    RdsInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: teste-backend-ticket-db-${self:provider.stage}
        DBInstanceClass: db.t3.micro
        Engine: postgres
        MasterUsername: ${self:custom.dbUser}
        MasterUserPassword: ${self:custom.dbPassword}
        AllocatedStorage: 20
        StorageType: gp2
        DBName: ${self:custom.dbName}
        PubliclyAccessible: true
        BackupRetentionPeriod: 7
        MultiAZ: false
        EnableCloudwatchLogsExports:
          - postgresql
        Tags:
          - Key: Name
            Value: teste-backend-ticket-db
          - Key: Environment
            Value: ${self:provider.stage}
